version: '3'
services:
  ragexplorer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/code
    working_dir: /code
    command: streamlit run app.py --server.port 8501
volumes:
 db: